packages:
  - projects/*

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - angular-extended-builder

ignoredBuiltDependencies:
  - less

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - lefthook
  - lmdb
  - msgpackr-extract
